name: AMT Result Checker Bot

permissions:
  contents: write

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:        # manual run button

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        # env:
        #   BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        #   CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python check.py

      - name: Commit state files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          if [[ -n "$(git status --porcelain seen.json users.json)" ]]; then
            git add seen.json users.json
            git commit -m "Update job checker state"
            git push
          else
            echo "No changes"
          fi
